import pandas as pd
import logging
from openpyxl import Workbook
from ..utils.paths import output_root, ts_root
from .helpers import norm_header, write_table, add_title_banner, autosize_columns


def generate_invoice_annex(month: str, target_clients: list = None):
    logger = logging.getLogger(__name__)
    logger.info(f"▶ Indítás: Számlamelléklet generálás - Hónap: {month}")

    # Normally this would load the summary generated by aggregator.py
    # For simplicity, we search for the latest summary file in the output folder
    summaries = sorted(output_root().glob(f"timesheet_summary_{month}_*.xlsx"))
    if not summaries:
        logger.error(
            f"Nem található összesített fájl a(z) {month} hónaphoz. Futtasd az Összesítést először!"
        )
        return None

    summary_path = summaries[-1]
    df = pd.read_excel(summary_path, sheet_name="Összesítés", skiprows=2)

    if target_clients:
        df = df[df["Ügyfélkód"].isin(target_clients)]

    if df.empty:
        logger.warning("Nincs adat a megadott szűrők alapján.")
        return None

    wb = Workbook()
    ws = wb.active
    ws.title = "Számlamelléklet"

    add_title_banner(ws, "Számlamelléklet", month, col_count=len(df.columns))
    write_table(ws, df, start_row=3)
    autosize_columns(ws)

    out_name = f"szamlamelleklet_{month}.xlsx"
    save_path = output_root() / out_name
    wb.save(save_path)

    logger.info(f"✅ Számlamelléklet elkészült: {out_name}")
    return save_path
